### ISSUE TITLE
Release workflow does not include deb file in latest-linux.yml

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#505]
This causes the `autoUpdater.checkForUpdates()` to return `null`.

In a `deb` app on Linux, the autoUpdater (probably) checks for the `latest-linux.yml` file to see if there is a new update. The contents of it are these:

```
version: 1.4.3
files:
  - url: Alephium-1.4.3.AppImage
    sha512: XBDYrxe1/17X2vdaruUkfqUMu4R9QmQt8rJ8muPX32YRSDh68+QQHktfMGYamTTx/hOIdKpFMit8fy7aOZRyNQ==
    size: 96005248
    blockMapSize: 101524
path: Alephium-1.4.3.AppImage
sha512: XBDYrxe1/17X2vdaruUkfqUMu4R9QmQt8rJ8muPX32YRSDh68+QQHktfMGYamTTx/hOIdKpFMit8fy7aOZRyNQ==
releaseDate: '2023-02-01T16:06:21.391Z'
```

I guess that because it only mentions `AppImage` in this file, the `deb` app does not find a new version and returns `null`.

If I run the `AppImage`, the update system works fine ✅
